name: New Scanner
on: workflow_dispatch

jobs:
  accessibility_scanner:
    runs-on: ubuntu-latest
    steps:
      - uses: github/accessibility-scanner@v2
        with:
          urls: | 
            https://accessibility-scanner-demo.netlify.app/
            https://accessibility-scanner-demo.netlify.app/contact.html
          repository: nmnishant/accessibility-scanner-demo
          token: ${{ secrets.GH_TOKEN }}
          cache_key: accessibility-scan-cache
